# Generated by Django 2.2.2 on 2019-06-30 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mastermind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_winner', models.BooleanField()),
                ('still_active', models.BooleanField()),
                ('match_time', models.TimeField()),
                ('codeBreaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchResume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('code_response', models.CharField(max_length=30)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mastermind.Mastermind')),
            ],
        ),
    ]
