# Generated by Django 2.2.2 on 2019-07-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastermind', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastermind',
            name='game_code',
            field=models.CharField(default='R-G-Y-B', max_length=255),
            preserve_default=False,
        ),
    ]
